version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwrd
      POSTGRES_DB: utpmatchdb
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-admin-network

  adminer:
    depends_on:
      - postgres
    image: adminer
    container_name: adminer-container
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - '8080:8080'
    networks:
      - app-admin-network

networks:
  app-admin-network:
